/**
 * Auto-generated catalogues + hand-written helpers for consuming
 * them from React components. Regenerated by scripts/content-build.ts.
 */
export * from './catalogue';
export type * from '../../../content/schema';
export {
  getPage,
  pageValue,
  microcopy,
  segmentCta,
  overlayCta,
  awarenessById,
  provocationById,
} from './helpers';
